### ISSUE TITLE
Auto-instrumentation of profiles with Pyroscope

### ISSUE THREAD

**Issue by swar8080** [grafana/grafana-opentelemetry-java#740]
### Is your feature request related to a problem? Please describe.

We currently use OpenTelemetry Operator to inject the OpenTelemetry java agent jar. That makes rollout to all our applications easy since we just need to add a pod annotation.

It would be great if we could also auto-inject pyroscope profiling to save teams from making [code changes](https://grafana.com/docs/pyroscope/latest/configure-client/language-sdks/java/#start-pyroscope-from-apps-java-code) to manually initialize it. 

### Describe the solution you'd like

Add an option to auto-initialize pyroscope when using the grafana opentelemetry java agent

**Comment by swar8080** [comment]
We ended-up using alloy to auto-profile applications without code changes https://github.com/grafana/pyroscope/blob/main/examples/grafana-agent-auto-instrumentation/java/kubernetes/grafana-alloy.yaml so not sure this is still needed

Although I saw OTEL profiling is now alpha, so maybe this is worth adding if/when the java OTEL sdk supports it

**Comment by zeitlinger** [comment]
Yes, I agree - let's close for now
